language: python
sudo: false
cache: pip
python:
  - "3.9"
install:
  - "pip install -e ."
  - "pip install sphinx==2.1.2"
  - "pip install sphinx-rtd-theme==0.4.3"

os:
  - linux
  - windows
script:
  - "cd test && pytest"
  - "cd ../docs && sphinx-build -W -b html -d _build/doctrees . _build/html"
